AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.1

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Layout/HashAlignment:
  EnforcedColonStyle: table

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
