language: ruby
cache: bundler

# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
sudo: false

rvm:
  - jruby-9.2.8.0
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - jruby-head
  - ruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true

before_install:
  - gem update --system --force
  - gem --version
  - gem install bundler

notifications:
  email: false
