language: ruby
cache: bundler

# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
sudo: false

rvm:
  - jruby-9.1.7.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-head
  - ruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true

before_install:
  - gem update --system
  - gem --version
  - gem install bundler

notifications:
  email: false
