name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        ruby: [ '2.3.x', '2.4.x', '2.5.x', '2.6.x' ]
    name: Test with Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
