name: Ruby

on:
  push:
  schedule:
  - cron:  '0 0 1 * *' # at 00:00 on the 1st of every month

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        ruby:
          - "2.1"
          - "2.2"
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "ruby-head"
          - "jruby"
          - "truffleruby"
        include:
          - os: windows-latest
            ruby: "2.4"
          - os: windows-latest
            ruby: "3.1"
        exclude:
          - os: windows-latest
            ruby: truffleruby
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: ruby -v
    - run: bundle install --jobs 4 --retry 3
    - run: bundle exec rake spec

  lint:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
    - run: ruby -v
    - run: bundle install --jobs 4 --retry 3
    - run: bundle exec rake rubocop

  install:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
    - run: ruby -v
    - run: gem build dyno_metadata
    - run: gem install *.gem
